const articles = [
    {
        name: 'learn-react',
        title: 'the fastest way to learn react',
        content: [
            `1lorem ipsum Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.

            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.

            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.

            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.
`
        ]
    },
    {
        name: 'learn-react2',
        title: 'the fastest way to learn react2',
        content: [
            `2lorem ipsum Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.

            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.

            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.

            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.
`
        ]
    },
    {
        name: 'learn-react3',
        title: 'the fastest way to learn react3',
        content: [
            `3lorem ipsum Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.

            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.

            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.

            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed dignissimos ipsa optio totam ad molestiae placeat consectetur? Assumenda magnam, numquam perferendis minus qui sit ullam sint ex, itaque dolor tempore. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Temporibus nobis pariatur aliquid ea consequuntur aut animi nostrum beatae velit dolore eos incidunt doloribus assumenda, ab dolor quod optio non blanditiis? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat harum error repellendus rem accusantium! Sunt libero perspiciatis eum aliquam blanditiis voluptate in fugit possimus. Cumque ullam sit eligendi tempore veritatis.
`
        ]
    }
]

export default articles;
